### ISSUE TITLE
9.2 is not compatible anymore?

### ISSUE THREAD

**Issue by kworr** [andy128k/pg-sphinx#2]
Just tried to compile on 9.2:

```
pg_sphinx.c:7:10: fatal error: 'access/htup_details.h' file not found
#include <access/htup_details.h>
         ^
1 error generated.
```
